model_kwargs:
  ckpt_path: 'checkpoints/OmniTokenizer/LLM/ucf_class_lm.ckpt'
  ignore_keys: ['first_stage_model', 'transformer.pos_emb']
  first_stage_key: "video"
  cond_stage_key: "label"
  pkeep: 1.0
  sos_token: 0
  vqvae_ckpt: ''
  caption_dim: 4096
  class_dropout_prob: 0.1
  vae_dim: 4

  gpt_args:
    class_cond_dim: 101
    cond_stage_vocab_size: 101
    vocab_size: 8192
    first_stage_vocab_size: 8192
    unconditional: false
    block_size: 25121
    n_layer: 24
    n_head: 16
    n_embd: 1536
    resolution: 256
    sequence_length: 17
    starts_with_sos: true
    p_drop_cond: 0.1
    vtokens: false
    vtokens_pos: false
    sample_every_n_latent_frames: 0
    class_first: false
    transformer_dropout: 0.
    n_unmasked: 0
    


